// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:myseries/config/api_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ApiKeys.tmdbApiKeyWeb,
    appId: '1:252562596550:web:96ab52facd7e936221edc7',
    messagingSenderId: '252562596550',
    projectId: 'myseries-42f59',
    authDomain: 'myseries-42f59.firebaseapp.com',
    storageBucket: 'myseries-42f59.firebasestorage.app',
    measurementId: 'G-0W1CNENX84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ApiKeys.tmdbApiKeyAndroid,
    appId: '1:252562596550:android:cea70f6ab605c77521edc7',
    messagingSenderId: '252562596550',
    projectId: 'myseries-42f59',
    storageBucket: 'myseries-42f59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiKeys.tmdbApiKeyIOS,
    appId: '1:252562596550:ios:b12733d27f0c418421edc7',
    messagingSenderId: '252562596550',
    projectId: 'myseries-42f59',
    storageBucket: 'myseries-42f59.firebasestorage.app',
    iosBundleId: 'com.example.myseries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ApiKeys.tmdbApiKeyIOS,
    appId: '1:252562596550:ios:b12733d27f0c418421edc7',
    messagingSenderId: '252562596550',
    projectId: 'myseries-42f59',
    storageBucket: 'myseries-42f59.firebasestorage.app',
    iosBundleId: 'com.example.myseries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: ApiKeys.tmdbApiKeyWeb,
    appId: '1:252562596550:web:0c1dbe39bc90712221edc7',
    messagingSenderId: '252562596550',
    projectId: 'myseries-42f59',
    authDomain: 'myseries-42f59.firebaseapp.com',
    storageBucket: 'myseries-42f59.firebasestorage.app',
    measurementId: 'G-W9ZC2J5L2D',
  );
}
